return {
  "nvim-treesitter/nvim-treesitter",
  lazy = true,
  event = "BufEnter",
  cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
  keys = {
    { "<C-Space>", desc = "Increment selection" },
    { "<BS>", desc = "Decrement selection" }
  },
  build = ":TSUpdate",
  config = function()
    local configs = require("nvim-treesitter.configs")
    configs.setup({
      ensure_installed = {
        "arduino",
        "asm",
        "bash",
        "bibtex",
        "c",
        "c_sharp",
        "cmake",
        "comment",
        "cpp",
        "css",
        "csv",
        "cuda",
        "diff",
        "dockerfile",
        "fish",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "glsl",
        "go",
        "gomod",
        "gpg",
        "groovy",
        "html",
        "http",
        "ini",
        "java",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        "json5",
        "jsonc",
        "kotlin",
        "latex",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "nginx",
        "nix",
        "passwd",
        "perl",
        "php",
        "properties",
        "python",
        "rasi",
        "regex",
        "ruby",
        "rust",
        "scss",
        "sql",
        "ssh_config",
        "tmux",
        "tsx",
        "typescript",
        "udev",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
        "zathurarc"
      },
      sync_install = false,
      highlight = { enable = true, },
      indent = { enable = true, },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<C-space>",
          node_incremental = "<C-space>",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
    })
  end
}
